export const HOTSPOTS = [
  {
    city: 'Lahore',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [74.3587, 31.5204],
  },
  {
    city: 'Islamabad',
    state: 'Islamabad',
    country: 'Pakistan',
    coordinates: [73.0551, 33.6844],
  },
  {
    city: 'Karachi',
    state: 'Sindh',
    country: 'Pakistan',
    coordinates: [67.0099, 24.8615],
  },
  {
    city: 'Faisalabad',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [73.135, 31.4504],
  },
  {
    city: 'Rawalpindi',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [73.0479, 33.5], // Adjusted to prevent overlap
  },
  {
    city: 'Peshawar',
    state: 'Khyber Pakhtunkhwa',
    country: 'Pakistan',
    coordinates: [71.5249, 34.0151],
  },
  {
    city: 'Multan',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [71.5249, 30.1575],
  },
  {
    city: 'Sialkot',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [74.5229, 32.4945],
  },
  {
    city: 'Quetta',
    state: 'Balochistan',
    country: 'Pakistan',
    coordinates: [67.0099, 30.1798],
  },
  {
    city: 'Hyderabad',
    state: 'Sindh',
    country: 'Pakistan',
    coordinates: [68.3738, 25.396],
  },
  {
    city: 'Sukkur',
    state: 'Sindh',
    country: 'Pakistan',
    coordinates: [68.857, 27.7052],
  },
  // --- NEW CITIES START HERE ---
  {
    city: 'Bahawalpur',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [71.7, 29.39],
  },
  {
    city: 'Bhopalwala',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [74.36, 32.43],
  },
  {
    city: 'Chak Jhumra',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [73.19, 31.56],
  },
  {
    city: 'Daska Kalan',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [74.35, 32.32],
  },
  {
    city: 'Eminabad',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [74.26, 32.04],
  },
  {
    city: 'Gujranwala',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [74.19, 32.1567],
  },
  {
    city: 'Hundal',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [74.52922, 32.42274],
  },
  {
    city: 'Jhang',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [72.33, 31.28],
  },
  {
    city: 'Jhelum',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [73.73, 32.94],
  },
  {
    city: 'Kahna Nau',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [74.369, 31.3671],
  },
  {
    city: 'Kasur',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [74.45, 31.1167],
  },
  {
    city: 'Kotli Loharan',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [74.5, 32.59],
  },
  {
    city: 'Lodhran',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [71.63, 29.55],
  },
  {
    city: 'Mandi Bahauddin',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [73.48, 32.58],
  },
  {
    city: 'Murree',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [73.39, 33.91],
  },
  {
    city: 'Pattoki',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [73.85, 31.02],
  },
  {
    city: 'Qadirpur Ran',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [71.66, 30.29],
  },
  {
    city: 'Rahim Yar Khan',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [70.3, 28.42],
  },
  {
    city: 'Raiwind',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [74.2169, 31.3654],
  },
  {
    city: 'Rojhan',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [70.13, 28.81],
  },
  {
    city: 'Sambrial',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [74.35, 32.48],
  },
  {
    city: 'Sheikhupura',
    state: 'Punjab',
    country: 'Pakistan',
    coordinates: [74.0, 31.71],
  },
  {
    city: "Khairpur Mir's",
    state: 'Sindh',
    country: 'Pakistan',
    coordinates: [68.76, 27.53],
  },
  {
    city: 'Mirpur Khas',
    state: 'Sindh',
    country: 'Pakistan',
    coordinates: [69.01, 25.51],
  },
  {
    city: 'Kharan',
    state: 'Balochistan',
    country: 'Pakistan',
    coordinates: [65.42, 28.59],
  },
  {
    city: 'Abbottabad',
    state: 'Khyber Pakhtunkhwa',
    country: 'Pakistan',
    coordinates: [73.2194, 34.1558],
  },
  {
    city: 'Haripur',
    state: 'Khyber Pakhtunkhwa',
    country: 'Pakistan',
    coordinates: [72.93, 33.99],
  },
  {
    city: 'Malam Jabba',
    state: 'Khyber Pakhtunkhwa',
    country: 'Pakistan',
    coordinates: [72.57, 34.8],
  },
];

export const FAKE_HOTSPOTS = [
  { city: 'Lahore', aqi: 165, pm25: 95.2 },
  { city: 'Islamabad', aqi: 45, pm25: 22.1 },
  { city: 'Karachi', aqi: 88, pm25: 35.8 },
  { city: 'Faisalabad', aqi: 120, pm25: 68.4 },
  { city: 'Rawalpindi', aqi: 75, pm25: 30.5 },
  { city: 'Peshawar', aqi: 140, pm25: 82.3 },
  { city: 'Multan', aqi: 95, pm25: 45.6 },
  { city: 'Sialkot', aqi: 85, pm25: 38.2 },
  { city: 'Quetta', aqi: 70, pm25: 32.4 },
  { city: 'Hyderabad', aqi: 110, pm25: 58.7 },
  { city: 'Sukkur', aqi: 90, pm25: 42.3 },
];
